application:
  port: 8000
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
email_client:
  base_url: "localhost"
  sender_email: "kristian.mohr@porthuset.dk"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"