application:
  port: 8000
email_client:
  base_url: "localhost"
  sender_email: "kmn1993@gmail.com"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"